baseurl: https://nyic.shop
copyright: © 2023 NYIC
languagecode: en-us
enablerobotstxt: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: vs
menu:
  main:
  - identifier: home
    name: Home
    weight: 10
    url: /
  - identifier: Shop
    name: Shop Information
    weight: 30
    url: /shop/
  - identifier: Memberships
    name: Memberships
    weight: 20
    url: /memberships/
  - identifier: Become a Member!
    name: Become a Member!
    weight: 40
    url: mailto:info@nyic.shop
  # - identifier: projects
  #   name: Projects
  #   weight: 50
  #   url: /projects/
paginate: 50
permalinks:
  blog: /blog/:year/:month/:day/:title/
social:
  # envelope: mailto:example@example.com
  # discord: https://discord.com/users/example
  github: https://github.com/nyic
  # facebook: https://facebook.com/example
  instagram: https://instagram.com/ny_industrial_collective
  # linkedin: https://www.linkedin.com/in/example
  # reddit: https://reddit.com/u/example
  # twitch: https://www.twitch.tv/example
  # twitter: https://twitter.com/example
  # youtube: https://www.youtube.com/user/example
theme: paige
timezone: America/New_York
title: New York Industrial Collective
titlecasestyle: Go
googleAnalytics: G-NKH1QF95EC